### ISSUE TITLE
Colours?

### ISSUE THREAD

**Issue by ser** [raujonas/executor#18]
Any chances to change font colour of parts of the output? It would be very helpful to spot some anomalies.

**Comment by raujonas** [comment]
Unfortunately this is currently not possible. Do you want to display a command always in a specific color or should the color by dynamic e.g. only if a certain condition is met?

**Comment by ser** [comment]
I was thinking about dynamic to be honest :-) Some parts white and some red for example.

**Comment by raujonas** [comment]
Finally got some time to take a look into this! What I came up with is the following: I introduced settings, which can be part of the command output now (e.g. `<executor.css.red>`). For example the following command queries the timestamp. If the output is a round number, the output should have the color red, if not then green.

`date +%s | awk '{if ($1 % 2 == 0) {print $1"<executor.css.red>"} else { print $1"<executor.css.green>"} }'`

The output looks then either like `1608105328<executor.css.red>` or `1608105329<executor.css.green>`. The setting will be removed from the final output of course.

The css can be specified in the new stylesheet.css:
```
.red {
    color: red;
}

.green {
    color: rgb(107, 179, 0);
}
```
Final output: 
![grafik](https://user-images.githubusercontent.com/25148277/102324769-91d6bd80-3f82-11eb-8750-614c16bff4cf.png)
![grafik](https://user-images.githubusercontent.com/25148277/102324791-9a2ef880-3f82-11eb-93ec-4bdddd6d5138.png)

This way you can specify the css like you want and add your custom `<executor.css.your-custom-class>`. It works also with multiple css classes. I think this is pretty cool because we use this for other things than css in the future.

What do you think about this solution? Would this fix your issue? I will test it further then.

**Comment by raujonas** [comment]
I will merge the PR for now and make a new release. If you have any questions or anything else feel free to tell me!

**Comment by ser** [comment]
I was sure I replied already before going for holiday - it's amazing and exactly what I need. Thanks!

**Comment by raujonas** [comment]
@ser happy to hear that! New version is already available on extensions.gnome.org.

**Comment by raujonas** [comment]
Hi @ser. With the latest version v12 you can also use markup to style the output. This makes the use of multiple colors in the same command possible for example (https://github.com/raujonas/executor#use-of-markup). Thought this might be interesting for you :blush:

**Comment by ser** [comment]
I can confirm  markup works really well :) Thank you!
