### ISSUE TITLE
View does not update when checked command returns no output

### ISSUE THREAD

**Issue by peterrus** [raujonas/executor#8]
I am using executor to run a script that in some cases returns output, and in some cases just exits with status code 0. If the scripts output changes from a state in which it did give output to a state in which it just exits without output, executor does not update it's view. 

As a workaround I made my script print an empty string using `echo ""`. This seems to resolve the problem. 

Using the latest version from Gnome Extensions (labeled 'version 1') on Ubuntu 20.04 on Gnome 3.36.3

**Comment by raujonas** [comment]
Hi. I remember that I had some issues with specific scripts back when I used "sh" for executing the commands. Because of that I switched later to "bash" [in this commit](https://github.com/raujonas/executor/commit/26913908c144b6ac3bfedf86c037041b65b1136b), but this is not yet part of the release, I will release v2 soon.

So you could just make that change on your local copy of the extension and see if this helps. Let me now if you need more information or any help.

**Comment by peterrus** [comment]
Hi @raujonas,

Thanks for the reply. I also tried wrapping the line in with `bash -c <the line>` to be sure it gets executed in bash, but this didn't make a difference. 

What I expect indeed is for the view to be empty. I have a script that return 'Virtual machine is running' when a VM is running and returns nothing when the VM is not running. Because nothing is returned the view does not seem to update (to a empty view). I took a quick look at the commit you linked and I suspect this line to be the troublemaker: https://github.com/raujonas/executor/commit/26913908c144b6ac3bfedf86c037041b65b1136b#diff-06f1274e40de25abda72d812b1cce86aR55.

**Comment by raujonas** [comment]
Hey @peterrus,

yes you are right, that seems more reasonable of course :) Thank you for pointing out this case, I expected always an output for my commands.

I will fix this with v2, I propose something like this:

```
    if (stdout) {
        stdout.split('\n').map(line => entries.push(line));
        entries.forEach(output => {
            outputAsOneLine = outputAsOneLine + output;
        });
    } else {
        outputAsOneLine = '';
    }
```
So it should be empty in your case and you don't need the echo in your script anymore

PS: I would be awesome if you could test version 2 of the extension (my last tester hopped off the boat unfortunately and I have only feedback from myself which is not optimal). 
It is more complex now because of the new features (results for left, center and right status bar location and multiple commands are executed independently) but you have to specify the commands as a json now. 

I'll fix it there, everything you have to know is in the readme on the master branch, but please let me know if there's anything wrong.

**Comment by peterrus** [comment]
Sure! I think I can give that a try somewhere in the next days. I will let you know. So no GUI to edit the commands currently? Because I see one on the screenshot in the readme (which looks nice btw!)

**Comment by raujonas** [comment]
No pressure, I'm happy to have a tester :) There's still the settings GUI as before, but there are 3 different text fields for each location. But a better solution is on the list, maybe it would be better to do this before releasing idk.

**Comment by peterrus** [comment]
Personally I would vouch for a GUI as it makes the extension way easier to user (and easier to discover). I would prefer a single command with a solid GUI (like the one in V1) over multiple commands with a somewhat rudimentary GUI (no offense meant ofc!). 
But the same goes for this: no pressure.

**Comment by raujonas** [comment]
No offense taken! :+1: 

I get what you're saying, but the multiple commands thing is also a user request which I think is pretty helpful (example: some heavy and slow commands can only be executed every hour which otherwise would slow down the whole execution process).

So the way to go is to create a good UI for the settings. I'll think about it and make a suggestion :blush:

**Comment by peterrus** [comment]
Hi @raujonas 

I have cloned the repo locally and tried to reproduce the issue, but it is still there. I think I've isolated the issue however.

If you let executor run a local script (say `~/script.sh`) which contains the following:
```
#!/usr/bin/env bash
uptime
exit 0
```
You will see that the uptime gets nicely updated every x seconds (depending on your interval). If we now change the `exit 0` line to `exit 1` the updating stops working. In other words. Executor seems to not update the view when a non zero status code is returned (an error occured).

**Comment by raujonas** [comment]
Hi @peterrus 

Thanks for the update. I will have a closer look into this tomorrow.

**Comment by raujonas** [comment]
Okay so there are two things on my mind:

1) I found out why the view is not empty after an error: [https://github.com/raujonas/executor/blob/master/extension.js#L316](https://github.com/raujonas/executor/blob/master/extension.js#L316)
Currently the callback will only be processed if the command was executed without error (error code 0). Important here is, that the command will NOT be rescheduled in an error case, otherwise a faulty command would be executed over and over again.
Nevertheless you're right, the view should be emptied in this case.

2) IMO it would be better not to use exit code 1 if your VM is not running because this does indicate that the script execution failed somehow. I think the solution you found echoing an empty string is what I would do here too.

What do you think?

**Comment by peterrus** [comment]
> that the command will NOT be rescheduled in an error case, otherwise a faulty command would be executed over and over again.
> Nevertheless you're right, the view should be emptied in this case.

Interesting, in that case I would show some kind of error message or visual feedback in the view. I did not expect this behavior. Personally I would like the command to just keep executing but I can understand your reasoning. 

Some informative message inside the extension settings and/or visual feedback at a failed command run would at least make sure users know this behavior is to be expected. They can then decide if they want to use `exit 0` as a 'workaround'.

**Comment by raujonas** [comment]
Ok you convinced me now! :+1: Command will be executed again now even if it "fails" with any exit code.

Example: "echao Executor works!" -> echo spelled wrong: results in an empty view for this command even if there was a correct output before (it gets cleared - this should be what you requested first) AND there is a hint in the logs 
(in my case: _Aug 27 15:53:32 **** gnome-shell[2025]: Executor: error in command "echao Executor works!": /bin/bash: echod: Befehl nicht gefunden_)

This would solve all the issues then right or did I miss something again? I'm not sure if this helps yet in your case with the VM example because I don't know the details.

In this case you mentioned above (with exit 1 instead), uptime would be executed over and over again but there would still be an "error" log in the journal because of exit code 1:
```
#!/usr/bin/env bash
uptime
exit 1
```
This is what I get now in the logs when I run the script: _Aug 27 16:01:27 **** gnome-shell[2025]: Executor: error in command "sh ~/script.sh": Vorgang nicht zulässig_

Would this be the correct behavior? If yes, I pushed the changes already, otherwise I'll have a look again. Or would it be better to execute the commands over and over again regardless the error code and with NO log instead?

**Comment by peterrus** [comment]
Boom! works perfectly! Vielen dank.

I think it is useful that you are logging execution errors, I didn't realize executor did that when I was debugging the problem initially (before opening this issue). Maybe for less technical users it might also help if you give them some visual feedback in the view itself ('Error executing' in red text? Just an idea). But that is something we could probably debate in another issue.

Just to clarify: 

- In the case of a non zero exit code: executor keeps trying indefinitely?
- In the case of a non zero exit code: executor logs the error?

If that is both the case I'd say this issue is resolved!

**Comment by raujonas** [comment]
Yes both is the case now! I really forgot to set the correct permissions (happens all the time) but it is working with them too.

The question now is, should I make a release with the current progress or do you think it's not usable without a better gui?

**Comment by peterrus** [comment]
I think it'd be better to first finish the GUI. You could maybe do a release with the new error handling behaviour but no need to do that just for me, I am running `master` and I can work with the JSON interface. But for other users the JSON interface, while being a stepping stone to some nice new features, might give somewhat of a degraded experience or steep learning curve.

Either way: thanks for your work thusfar 🙏

-------- Original Message --------

**Comment by raujonas** [comment]
You're welcome! Thanks for your help and feedback. I'm more than happy that some people are using this.

I'll close this ticket for now and start working on the gui next.
